#!/bin/bash
# zfs-snap-pac

set -e
##############################
#   Variables
##############################
bootfs="none"
snapshotName="os-update-"


##############################
#   Main Script Part
##############################
#
# get rootfs from zpool parameter bootfs
bootfs=$(zpool get bootfs -o value -pH)

if [ "$bootfs" == "none" ]
then
    echo "Could not get BOOTFS/Root dataset! Stopping..."
    exit 1
fi

#
# get how many snapshots we already have
snapshotcount=$(zfs list -t snapshot -o name -pH $( echo -e "$bootfs" | wc -l))

if [ "$snapshotcount" == 0 ]; then
    echo "No snapshots found yet. Creating first snapshot..."

    #
    # TODO: 
    # - create snapshot
    # - add refind extra menu for snapshots
    # - add first snapshot to refind
    #
else
    echo "Found $snapshotcound existing snapshots."
    #
    # TODO:
    # - inrement snapshotcound
    # - create snapshot
    # - add snapshot to refind
fi
